version: '3.9'

services:
    app:
        image: node:lts
        working_dir: /node/app
        tty: true
        command: tail -f /dev/null
        volumes:
            - ../:/node/app
        ports:
            - 4000:4000
